import { useState } from "react";
import Head from "next/head";
import Script from "next/script";

import Video from "../components/Video";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [hlsSupported, setHlsSupported] = useState(false);
  return (
    <div className={styles.container}>
      <Script
        src="https://cdn.jsdelivr.net/npm/hls.js@latest"
        onLoad={() => {
          if (Hls.isSupported()) {
            setHlsSupported(true);
          }
        }}
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hallo</h1>
        {hlsSupported ? <Video /> : null}
      </main>
    </div>
  );
}
